### ISSUE TITLE
404 on valid user

### ISSUE THREAD

**Issue by gkiko** [freeuni-sdp/xo-achiev#15]
sandro1 და gkiko ვათამაშე და ერთერთმა გაიმარჯვა. xo-achiev `404`-ს მიბრუნებს ორივე მოთამაშის ინფორმაციაზე. @toka16 @GROX13

**Comment by GiorgiGagnidze** [comment]
თამაშის დასრულების მერე, ჯერ get გამოიძახე თუ put?

**Comment by GiorgiGagnidze** [comment]
თუ ჯერ get გამოიძახე მაშინ სწორი ყოფილა. ამ მომხმარებლებზე ჯერ არ არის ინფორმაცია, ანუ 404 = 0 score

**Comment by gkiko** [comment]
არ უწერიათ ჯერ. [code](https://github.com/freeuni-sdp/xo-game/blob/master/src/main/java/ge/edu/freeuni/sdp/xo/game/ArchiveUpdater.java#L68)
